# roles/docker_app_preinstaller/defaults/main.yaml

app_state: present
app_name: ""
app_parent_dir: "{{ docker_app_default_path }}" # defaults to /src/docker
app_user: ""
svc_volumes: 
  bind_mounts: []
  files: {}
compose_definition: {}
compose_pull: always
compose_recreate: auto
app_has_dockerfile: false