docker_app: samba
docker_app_desired_state: present
ufw_rules:
  - rule: allow
    proto: tcp
    port: "445"
    from_ip: 192.168.0.0/24
    to_ip: "{{ ansible_host }}"
    comment: Allow SMB from local domain
