---
# roles/install_software/tasks/main.yaml

#- name: Update and upgrade apt packages
#  become: true
#  apt:
#    upgrade: yes
#    update_cache: yes
#    cache_valid_time: 86400 #One day

- name: Install package
  ansible.builtin.apt:
    name: "{{item.package}}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ software }}"
  when: item.package != None

- name: Make sure daemon is running
  ansible.builtin.systemd:
    name: "{{item.package}}"
    state: started
    enabled: "{{ item.enabled | default(omit) }}"
  loop: "{{ software }}"
  when: (item.package is defined and item.package) and (item.check_svc is defined and item.check_svc)

  