# microserver/subtasks/configure_service_accounts.yml

- name: Ensure service user exists.
  ansible.builtin.include_role:
    name: system_user
  vars:
    user_name: "{{ item.name }}"
    user_groups: "{{ item.groups }}"
    user_comment: "{{ item.comment }}"
    state: "{{ item.state | default(omit) }}"
  loop:
    "{{ svc_accounts.values() | list }}"