
- name: Ansible | Load variables for current host
  ansible.builtin.include_vars:
    file: defaults/{{ task_name }}

- name: Filesystem | Create required filestructure
  ansible.builtin.include_tasks:
    file: directory_create.yaml
  when: docker_directories

- name: Linux | Create docker user
  ansible.builtin.include_tasks:
    file: user_create.yaml
  when: docker_user is defined or docker_group is defined