
- name: Ansible | Set empty app vars
  ansible.builtin.include_vars:
    file: defaults/docker_app_empty.yaml

- name: Ansible | Load variables for current docker app
  ansible.builtin.include_vars:
    file: defaults/{{ current_app }}
    
- name: Ubuntu | Filesystem | Create required filestructure
  ansible.builtin.include_tasks:
    file: docker_apps/directory_create.yaml
  when: docker_directories is defined and docker_directories | length > 0

- name: Ubuntu | Users | Create docker user
  ansible.builtin.include_tasks:
    file: user_create.yaml
  when: docker_user is defined or docker_group is defined

- name: Ubuntu | UFW Firewall | Samba Firewall config
  include_role:
    name: ufw_config
  vars:
    ruleset: "{{ ufw_rules }}"
  when: ufw_rules is defined
