# roles/docker_app/tasks/secrets.yaml
---

- name: Docker | Secret
  community.docker.docker_secret:
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    labels: "{{ item.labels | default(omit) }}"
    state: present
  loop: "{{ docker_app.secrets }}"
  when: docker_app.secrets is defined and docker_app.secrets != {}